name: Build Notebook Container
on: [push] # You may want to trigger this Action on other things than a push.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    #- name: update jupyter dependencies with repo2docker
    #  uses: jupyterhub/repo2docker-action@master
    #  with:
    #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #    REPO_DIR: /tmp
    #    NOTEBOOK_USER: roussman
    
    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.23)
        buildcache: true  # Configure oci://ghcr.io/spack/github-actions-buildcache
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack
    - run: spack containerize > Dockerfile
  # - run:  spack -e . install
    
    #- name: Create Dockerfile
    #  run: 

    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $username -p $password 
    - name: build the docker image
      id: build-docker-image
      run: |
        ls -la 
        docker build . -f Dockerfile -t dhruvin30/pytudes:latest
    - name: push the docker image
      id: push-docker-image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/pytudes:latest
